name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

env:
  PLUGIN_NAME: attachment-management

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # - name: Get Tag
      #   run: |
      #     echo "ACTION_TAG=$(git tag --sort version:refname | tail -n 1)" >> "$GITHUB_ENV"

      - name: Build
        id: build
        run: |
          npm install
          npm run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip ${{ env.PLUGIN_NAME }}
          ls

      - name: Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "main.js,manifest.json,${{ env.PLUGIN_NAME }}.zip"
